language: crystal

services:
  - docker

before_install:
  - docker run --net="host" -p "29015:29015" -p "28015:28015" -d rethinkdb:2.4

install:
  - shards install

env:
  - RETHINKDB_HOST=localhost

script:
  - crystal spec --error-trace
  - crystal tool format --check
  - bin/ameba
